# Generated by Django 5.1.6 on 2025-03-25 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oaauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oauser',
            options={'ordering': ('-date_joined',)},
        ),
    ]
